### ISSUE TITLE
write up README

### ISSUE THREAD

**Issue by kangkyu** [LARailsLearners/youtube-search-example#9]
this is a demo app for [youtube-search](https://github.com/LARailsLearners/youtube-search). It makes a simple API call to youtube, and saves search result to database. A user can keep search words and check daily search result on the pages. Each word has its own show page, and it has 5 search results. Currently by Heroku scheduler it runs a rake task and takes snapshot of search once a day. And (even though we are not sure to keep this feature in the future) it still has a button  on the page to run a search. There are features to build and nothing much has been decided. We became to start this project because we need a Rails app to use the gem for developing `youtube-search` gem.

### How to run

```
git clone
cd
bundle install
rails s
```

### How to contribute

Feel free to open pull requests or issues, and participate the discussion. This is being developed as a group project of [LARailsLearners](https://github.com/larailslearners), LA Eastside Ruby Rails Study Group.

**Comment by eaglerockdude** [comment]
I see thanks. 

what meetup is the best to attend?

I am in eaglerock.

**Comment by kangkyu** [comment]
@eaglerockdude it looks like currently this LA Eastside Ruby Rails Study Group does not have upcoming schedule. By the way, this project is being developed by remote participation, and it's on Github. We also have Slack channel `#east_side_study_group` in laruby.slack.com

**Comment by kangkyu** [comment]
updated README as above.
